version: '3'
services:
            
 db:
    image: mysql:8.3
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD : test
     MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    networks:
      app-network:
        ipv4_address: 172.20.0.5
 phpMyAdmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY : 1
    networks:
      - app-network
    ports:
      -  "8080:80"
    depends_on:
      - db
 app :
    build :
      context : .
      dockerfile : Dockerfile
    networks:
      - app-network
    ports :
      - 3000:3000
    volumes :
      - .:/app 
      - '/app/node_modules'
networks:
 app-network:
     ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
volumes:
  db_data: